name: triger with API call

on:
  repository_dispatch:
    types: [incident_report]

jobs:
  incident-handring:
    runs-on: ubuntu-latest
    steps:
      - name: handle-the-incident
        run: echo "incident was handeled"
