name: manual workflow test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "chose environment"
        required: true
        type: choice
        options:
          - staging
          - deployment
          - production
        default: "staging"

jobs:
  deploy_test:
    runs-on: ubuntu-latest
    steps:
      - name: check the manual workflow
        run: echo "this case to check the manual workflow ${{ inputs.environment }}"

