name: schedule workflow

on:
  schedule:
    - cron: "57 * * * *"
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test the schedule
        run: echo "this is to chek the cron job"


